_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.13.2
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 48
                - 49
                - 53
                - 63
            "2":
                - 1
                - 5
                - 11
                - 41
                - 48
                - 49
                - 53
                - 63
            "3":
                - 55
                - 61
            "4": 3.13.2
            "5": 0.20.1
            "6": 4.52.4
            "12": 0.20.1
            "13": linux-x86_64
